name: Upload Server

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./GradioApp

    steps:
      - name: Check Out
        uses: actions/checkout@v4

      - name: Set up Python 3.12.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.12.11"

      - name: update & install
        run: |
          sudo apt-get update
          sudo apt-get install curl

      - name: Install huggingface_cli
        run: curl -LsSf https://hf.co/cli/install.sh | bash

      - name: Download model
        run: |
          hf auth login --token "${{ secrets.HF_TOKEN }}"
          hf download Nuvantim/maxim_sentiment_analysis_model maxim-sentiment-models.onnx label_encoder.pkl maxim_fasttext.vec --local-dir models

      - name: install pex
        run: |
          pip install pex
          pex -r requirements.txt -o app.pex

      - name: archive all file
        run: 7z a maxim.7z app.py app.pex models/
        
      - name: transfer file
        uses: nogsantos/scp-deploy@master
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          user: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          remote: ./root
          src: ./GradioApp/app.py
          
